### ISSUE TITLE
Convert Managing Widgets Lesson Plan

### ISSUE THREAD

**Issue by JulieKuehl** [wptrainingteam/managing-widgets#1]
Convert Lesson Plan to GitHub

- [x]  copy and paste from Make site
- [x]  clean up the Markdown
- [x]  download the old images
- [x]  upload the images into GitHub
- [x]  swap out the image links

**Comment by JulieKuehl** [comment]
https://make.wordpress.org/training/handbook/user-lessons/managing-widgets/

**Comment by man4toman** [comment]
[Update] Convert Lesson Plan to GitHub

- [x] copy and paste from Make site
- [x] clean up the Markdown
- [x] download the old images
- [x] upload the images into GitHub
- [x] swap out the image links

Related PR #5
