### ISSUE TITLE
 All images goes 404

### ISSUE THREAD

**Issue by man4toman** [wptrainingteam/managing-widgets#2]
Hi @JulieKuehl
All images in lesson are 404.
Are they screenshot?
If they are screenshot I can start add new images instead them.

**Comment by JulieKuehl** [comment]
They likely were screenshots. If you could replace them with new images, that would be fantastic!

**Comment by man4toman** [comment]
Well, I will replace them.

**Comment by man4toman** [comment]
#3

**Comment by man4toman** [comment]
This issue fixed based on #3
